-- 코드를 입력하세요
SELECT *
FROM (
    SELECT A.CAR_ID, A.CAR_TYPE,
        ROUND(A.DAILY_FEE * 30 * ((100-IFNULL(B.DISCOUNT_RATE,0))/100)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR A
        LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON A.CAR_TYPE = B.CAR_TYPE
            AND B.DURATION_TYPE LIKE '30%'
    WHERE A.CAR_TYPE IN ('SUV', '세단')
        AND NOT EXISTS(
            SELECT X.CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY X
            WHERE X.END_DATE >= '20221101'
                AND X.CAR_ID = A.CAR_ID
        )
) Z
WHERE Z.FEE >= 500000
    AND Z.FEE < 2000000
ORDER BY Z.FEE DESC, Z.CAR_TYPE, Z.CAR_ID DESC
