-- 코드를 입력하세요
SELECT DATE_FORMAT(Z.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, Z.PRODUCT_ID, Z.USER_ID, Z.SALES_AMOUNT
FROM (
    SELECT A.SALES_DATE, A.PRODUCT_ID, A.USER_ID, A.SALES_AMOUNT
    FROM ONLINE_SALE A
    WHERE DATE_FORMAT(A.SALES_DATE, '%Y%m') = '202203'
    UNION
    SELECT B.SALES_DATE, B.PRODUCT_ID, NULL AS USER_ID, B.SALES_AMOUNT
    FROM OFFLINE_SALE B
    WHERE DATE_FORMAT(B.SALES_DATE, '%Y%m') = '202203'
) Z
ORDER BY Z.SALES_DATE, Z.PRODUCT_ID, Z.USER_ID
;