-- 코드를 입력하세요
SELECT A.BOOK_ID, DATE_FORMAT(A.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK A
WHERE DATE_FORMAT(A.PUBLISHED_DATE, '%Y') = '2021'
    AND A.CATEGORY = '인문'
ORDER BY A.PUBLISHED_DATE