-- 코드를 입력하세요
SELECT A.MEMBER_ID, A.MEMBER_NAME, A.GENDER, DATE_FORMAT(A.DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE A
WHERE DATE_FORMAT(A.DATE_OF_BIRTH, '%m') = '03'
    AND A.GENDER = 'W'
    AND A.TLNO IS NOT NULL
ORDER BY A.MEMBER_ID;